### PR TITLE
Fix rebalance leverage ratio

### LINKED ISSUE #14: Fix leverage ratio to account for okex perpetual swap inverse contract margin
The current leverage ratio tracks liability vs collateral and does a good job of accounting for capital requirements in that regard.
But it is almost insensitive to price movement which affects margin ratio of the inverse perpetual swap and the risk of liquidation on one side.
The goal is to account for both and insure safe margin posting when the price moves against the position.

Note:
Given that we take the swap position to hedge USD on the BTC down side, the risk of liquidation is on the BTC upside.
Depending on the effectiveness of the hedge and the funding fees (both eroding the swap position against the USD notional to be hedged) it could be tolerable to let the liquidation event happen (unless cheaper in trading fees to unwind manually) then take a new hedge position at the current price level. Versus pouring more BTC collateral against the original swap position to fend off liquidation.

### PR DESCRIPTION
**Pull request by sebastienverreault**
Fix #14 by changing account configuration from Isolated to Cross Margin Mode in order to allow for dynamic use of all funds (balance) on the account to act as collateral to the net position.

This simplifies funds and margin management into one action (transferring funds to the account to act as collateral) otherwise fund transfers and collateral posting to the margin are independent steps.
In the Isolated mode, the margin is set when initial position is open and does not change unless actively manipulated.
In the Cross mode, the margin changes as the market conditions and account balance change.

### CODE REVIEW

File: src/Dealer.ts [hunk 1]
```diff
@@ -186,7 +186,8 @@ export class Dealer {
         const originalPosition = updatedPositionResult.value.originalPosition
         const updatedPosition = updatedPositionResult.value.updatedPosition
 
-        exposureInUsd = updatedPosition.exposureInUsd
+        if (updatedPosition) exposureInUsd = updatedPosition.exposureInUsd
```
Comment (nicolasburtey) [inline src/Dealer.ts:189]: you should always use `{ }` around `if / else` this can avoid bugs when doing auto merging.

Comment (sebastienverreault) [reply src/Dealer.ts]: good catch thx & done!
